services:
  chatwave:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatwave-app
    expose:
      - "3000"
      - "3001"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SOCKET_PORT=3001
    restart: unless-stopped

  kingplay-api:
    build:
      context: ../kingplay-backend
    container_name: kingplay-api
    expose:
      - "5000"
    env_file:
        - ../kingplay-backend/.env
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - chatwave
      - kingplay-api
    restart: unless-stopped